workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: always

stages:
  - run

update-catalogue:
  stage: run
  script:
    - npm install
    - npm run start
  artifacts:
    paths:
      - results/*.html
